version: '3.1'
services: 
  aster-db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariaroot
      MYSQL_USER: useraster
      MYSQL_PASSWORD: mariapass
      MYSQL_DATABASE: dbaster
    volumes: 
      - aster_data:/var/lib/mysql
  mssqldb:
    image: "microsoft/mssql-server-linux:latest"
    hostname: "dockersqlserver"
    environment:
      SA_PASSWORD: "StrongPassw0rd"
      MSSQL_PID: Developer
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'
volumes: 
  aster_data: